### PR TITLE
chore: stop relying on fs and path to load sql scripts

### PR DESCRIPTION
**Pull request by gjuchault**
:wave: Hello

We've been recently trying to migrate our codebase to esbuild in bundling mode, and we've experienced issues with marv-pg-driver since it relies on `fs` to load sql scripts. Since everything (including node_modules code) is bundled into a single `index.js`, marv-pg-driver can't locate the sql scripts.

By moving sql files into regular js ones, we can now use this plugin even if bundled

### CODE REVIEW

**Comment by cressie176** [comment]
Hi @gjuchault,

Thanks for the PR, will give it some thought.

**Comment by cressie176** [comment]
Sorry for slow response on this. The reason for the delay is because I'm in two minds whether to accept or reject. On one hand the change is minor and will solve the problem you have with bundling, on the other I'm instinctively against repackaging a SQL file as a JavaScript module in order to circumvent a limitation with an external bundling tool. There are legitimate reasons to include non js/json assets in libraries, and while this may be uncommon, I suspect many libraries do. The responsibility should therefore be on the bundling tool to support this use case rather than implement workarounds in each of the impacted libraries.

What's your take @BorePlusPlus ?

**Comment by BorePlusPlus** [comment]
Not likely going to be of much help here, as I am just as conflicted. 

If pushed, then I guess I'm leaning on the side not repacking the SQL files for the reasons you mentioned @cressie176 and the fact that writing a module for marv is not that complex that an interested party couldn't fork their own if they'd like different behaviour or implementation.
At the same time, I must admit that changing the file loading mechanism doesn't change the behaviour, so it may be acceptable. If I was to go for it I might use `.sql.js` file extension to be able to `require('./sql/unlock.sql')` to make it more explicit what's being required.

---

A driveby side comment - the PR does some, by the looks of it, unnecessary reformating of test code.

**Comment by gjuchault** [comment]
Good points. I'm aware on the challenge of adapting your code to different bundlers or not do that. I did the change in a fork just because I actually needed it, but I'm fine if you don't merge it, it's good if other people are looking for it, they can find the ressource here.

Agreed on the `.sql.ts` and sorry for the editor auto formatting, I'll fix that in a minute :)

**Pull request closed without merging**
